name: dovetonfletcher
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5339773031882942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3125
  lightness: 0.5231063843239099
  saturation: 0.875
  rhythmicContrast: 0.4204087881371379
purpose: []
